package com.newtouch.blockchain.entity;

import com.newtouch.blockchain.mybatis.BaseEntity;
import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_EMAIL_RECORD
 */
@ToString(callSuper=true, doNotUseGetters=true)
public class EmailRecord extends BaseEntity implements Serializable {
	
	//链接未使用过
		public static final String CODE_UNUSED="0";
		//链接使用过
		public static final String CODE_USED="1";
		
		//无链接
		public static final String CODE_NO="2";
		
		//注册
		public static final String TYPE_REGISTER = "01";
		//忘记密码
		public static final String TYPE_FORGER = "02";
		//重置密码
		public static final String TYPE_REVIEW = "03";
		//交易提醒
		public static final String TYPE_TRANSACTION = "04";
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMAIL_RECORD.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMAIL_RECORD.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_EMAIL_RECORD.OUTDATE
     *
     * @mbg.generated
     */
    private LocalDateTime outdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_EMAIL_RECORD
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMAIL_RECORD.TYPE
     *
     * @return the value of TBL_EMAIL_RECORD.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMAIL_RECORD.TYPE
     *
     * @param type the value for TBL_EMAIL_RECORD.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMAIL_RECORD.EMAIL
     *
     * @return the value of TBL_EMAIL_RECORD.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMAIL_RECORD.EMAIL
     *
     * @param email the value for TBL_EMAIL_RECORD.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMAIL_RECORD.STATUS
     *
     * @return the value of TBL_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMAIL_RECORD.STATUS
     *
     * @param status the value for TBL_EMAIL_RECORD.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_EMAIL_RECORD.OUTDATE
     *
     * @return the value of TBL_EMAIL_RECORD.OUTDATE
     *
     * @mbg.generated
     */
    public LocalDateTime getOutdate() {
        return outdate;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_EMAIL_RECORD.OUTDATE
     *
     * @param outdate the value for TBL_EMAIL_RECORD.OUTDATE
     *
     * @mbg.generated
     */
    public void setOutdate(LocalDateTime outdate) {
        this.outdate = outdate;
    }
}