package com.newtouch.blockchain.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.newtouch.blockchain.mybatis.BaseEntity;

import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_TX_RECORD
 */
@ToString(callSuper=true, doNotUseGetters=true)
public class TxRecord extends BaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   交易发起方
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.ACCOUNT_FROM
     *
     * @mbg.generated
     */
    private String accountFrom;

    /**
     * Database Column Remarks:
     *   交易接收方
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.ACCOUNT_TO
     *
     * @mbg.generated
     */
    private String accountTo;

    /**
     * Database Column Remarks:
     *   交易数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   交易hash
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.HASH
     *
     * @mbg.generated
     */
    private String hash;

    /**
     * Database Column Remarks:
     *   交易时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.TRANS_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime transTime;
    
    /**
     * Database Column Remarks:
     *   所属块编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.BLOCK_NUMBER
     *
     * @mbg.generated
     */
    private Long blockNumber;
    
    /**
     * Database Column Remarks:
     *   交易序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.NONCE
     *
     * @mbg.generated
     */
    private Long nonce;
    
    /**
     * Database Column Remarks:
     *   交易数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_TX_RECORD.GASPRICE
     *
     * @mbg.generated
     */
    private BigDecimal gasprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database Column Remarks:
     *   交易发起方
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TX_RECORD.ACCOUNT_FROM
     *
     * @return the value of TBL_TX_RECORD.ACCOUNT_FROM
     *
     * @mbg.generated
     */
    public String getAccountFrom() {
        return accountFrom;
    }

    /**
     * Database Column Remarks:
     *   交易发起方
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TX_RECORD.ACCOUNT_FROM
     *
     * @param accountFrom the value for TBL_TX_RECORD.ACCOUNT_FROM
     *
     * @mbg.generated
     */
    public void setAccountFrom(String accountFrom) {
        this.accountFrom = accountFrom == null ? null : accountFrom.trim();
    }

    /**
     * Database Column Remarks:
     *   交易接收方
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TX_RECORD.ACCOUNT_TO
     *
     * @return the value of TBL_TX_RECORD.ACCOUNT_TO
     *
     * @mbg.generated
     */
    public String getAccountTo() {
        return accountTo;
    }

    /**
     * Database Column Remarks:
     *   交易接收方
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TX_RECORD.ACCOUNT_TO
     *
     * @param accountTo the value for TBL_TX_RECORD.ACCOUNT_TO
     *
     * @mbg.generated
     */
    public void setAccountTo(String accountTo) {
        this.accountTo = accountTo == null ? null : accountTo.trim();
    }

    /**
     * Database Column Remarks:
     *   交易数量
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TX_RECORD.AMOUNT
     *
     * @return the value of TBL_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Database Column Remarks:
     *   交易数量
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TX_RECORD.AMOUNT
     *
     * @param amount the value for TBL_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Database Column Remarks:
     *   交易hash
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TX_RECORD.HASH
     *
     * @return the value of TBL_TX_RECORD.HASH
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * Database Column Remarks:
     *   交易hash
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TX_RECORD.HASH
     *
     * @param hash the value for TBL_TX_RECORD.HASH
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * Database Column Remarks:
     *   交易时间
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_TX_RECORD.TRANS_TIME
     *
     * @return the value of TBL_TX_RECORD.TRANS_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getTransTime() {
        return transTime;
    }

    /**
     * Database Column Remarks:
     *   交易时间
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_TX_RECORD.TRANS_TIME
     *
     * @param transTime the value for TBL_TX_RECORD.TRANS_TIME
     *
     * @mbg.generated
     */
    public void setTransTime(LocalDateTime transTime) {
        this.transTime = transTime;
    }
    /**
     * Database Column Remarks:
     *   所属块编号
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.BLOCK_NUMBER
     *
     * @return the value of TBL_TX_RECORD.BLOCK_NUMBER
     *
     * @mbg.generated
     */
    public Long getBlockNumber() {
        return blockNumber;
    }

    /**
     * Database Column Remarks:
     *   所属块编号
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.BLOCK_NUMBER
     *
     * @param blockNumber the value for TBL_TX_RECORD.BLOCK_NUMBER
     *
     * @mbg.generated
     */
    public void setBlockNumber(Long blockNumber) {
        this.blockNumber = blockNumber;
    }

	public Long getNonce() {
		return nonce;
	}

	public void setNonce(Long nonce) {
		this.nonce = nonce;
	}

	public BigDecimal getGasprice() {
		return gasprice;
	}

	public void setGasprice(BigDecimal gasprice) {
		this.gasprice = gasprice;
	}
    
    
}