package com.newtouch.blockchain.entity;

import com.newtouch.blockchain.mybatis.BaseEntity;
import java.io.Serializable;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_WALLET_ACCOUNT
 */
@ToString(callSuper=true, doNotUseGetters=true)
public class WalletAccount extends BaseEntity implements Serializable {
	
	//已激活
	public static final String STATUS_YES = "1";
	//未激活
	public static final String STATUS_NO = "0";
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_ACCOUNT.ADDRESS
     *
     * @mbg.generated
     */
    private String address;
    
    private String name;
    
    private String phone;
    
    private String status = STATUS_YES;
    
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_ACCOUNT.USERNAME
     *
     * @return the value of TBL_WALLET_ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_ACCOUNT.USERNAME
     *
     * @param username the value for TBL_WALLET_ACCOUNT.USERNAME
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_ACCOUNT.PASSWORD
     *
     * @return the value of TBL_WALLET_ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_ACCOUNT.PASSWORD
     *
     * @param password the value for TBL_WALLET_ACCOUNT.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_ACCOUNT.ADDRESS
     *
     * @return the value of TBL_WALLET_ACCOUNT.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_ACCOUNT.ADDRESS
     *
     * @param address the value for TBL_WALLET_ACCOUNT.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
    
    
}