package com.newtouch.blockchain.entity;

import com.newtouch.blockchain.mybatis.BaseEntity;
import java.io.Serializable;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_WALLET_CURRENCY
 */
@ToString(callSuper=true, doNotUseGetters=true)
public class WalletCurrency extends BaseEntity implements Serializable {
	
	//启用
	public static final String STATUS_YES = "1";
	//禁用
	public static final String STATUS_NO = "0";
	
	//天天服务链积分
	public static final String TYPE_SYSTEM_POINT = "1";
	//以太坊公链主币
	public static final String TYPE_ETHEREUM_PUBLIC_CHAIN_COIN = "2";
	//以太坊公链token
	public static final String TYPE_ETHEREUM_PUBLIC_CHAIN_TOKEN = "3";
	//以太坊私链主币
	public static final String TYPE_ETHEREUM_PRIVATE_CHAIN_COIN = "4";
	//以太坊私链token
	public static final String TYPE_ETHEREUM_PRIVATE_CHAIN_TOKEN = "5";
	//其他
	public static final String TYPE_OTHER = "5";
	
    /**
     * Database Column Remarks:
     *   币种符号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_CURRENCY.SYMBOL
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * Database Column Remarks:
     *   币种名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_CURRENCY.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   合约地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_CURRENCY.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    private String contractAddress;
    
    private String total;
    
    private String status;
    
    private String filePath;
    
    private String defaultPassword;
    
    private String fileName;
    
    private String password;
    
    private String type;
    
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database Column Remarks:
     *   币种符号
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_CURRENCY.SYMBOL
     *
     * @return the value of TBL_WALLET_CURRENCY.SYMBOL
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Database Column Remarks:
     *   币种符号
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_CURRENCY.SYMBOL
     *
     * @param symbol the value for TBL_WALLET_CURRENCY.SYMBOL
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * Database Column Remarks:
     *   币种名称
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_CURRENCY.NAME
     *
     * @return the value of TBL_WALLET_CURRENCY.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * Database Column Remarks:
     *   币种名称
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_CURRENCY.NAME
     *
     * @param name the value for TBL_WALLET_CURRENCY.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * Database Column Remarks:
     *   合约地址
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_CURRENCY.CONTRACT_ADDRESS
     *
     * @return the value of TBL_WALLET_CURRENCY.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * Database Column Remarks:
     *   合约地址
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_CURRENCY.CONTRACT_ADDRESS
     *
     * @param contractAddress the value for TBL_WALLET_CURRENCY.CONTRACT_ADDRESS
     *
     * @mbg.generated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getDefaultPassword() {
		return defaultPassword;
	}

	public void setDefaultPassword(String defaultPassword) {
		this.defaultPassword = defaultPassword;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNodeId() {
		return nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}
	
	
	
}