package com.newtouch.blockchain.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.newtouch.blockchain.mybatis.BaseEntity;

import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TBL_WALLET_BS_TX_RECORD
 */
@ToString(callSuper=true, doNotUseGetters=true)
public class WalletBsTxRecord extends BaseEntity implements Serializable {
	//默认状态
	public static final String STATUS_DEFAULT = "2";
	//成功
	public static final String STATUS_SUCCESS = "1";
	//失败
	public static final String STATUS_FAILED = "0";
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.FROM_USER
     *
     * @mbg.generated
     */
    private String fromUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.FROM_ADDRESS
     *
     * @mbg.generated
     */
    private String fromAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.TO_USER
     *
     * @mbg.generated
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.TO_ADDRESS
     *
     * @mbg.generated
     */
    private String toAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_WALLET_BS_TX_RECORD.TRAN_TIME
     *
     * @mbg.generated
     */
    private LocalDateTime tranTime;
    
    private String hash;
    
    private String currencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.FROM_USER
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.FROM_USER
     *
     * @mbg.generated
     */
    public String getFromUser() {
        return fromUser;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.FROM_USER
     *
     * @param fromUser the value for TBL_WALLET_BS_TX_RECORD.FROM_USER
     *
     * @mbg.generated
     */
    public void setFromUser(String fromUser) {
        this.fromUser = fromUser == null ? null : fromUser.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.FROM_ADDRESS
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.FROM_ADDRESS
     *
     * @mbg.generated
     */
    public String getFromAddress() {
        return fromAddress;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.FROM_ADDRESS
     *
     * @param fromAddress the value for TBL_WALLET_BS_TX_RECORD.FROM_ADDRESS
     *
     * @mbg.generated
     */
    public void setFromAddress(String fromAddress) {
        this.fromAddress = fromAddress == null ? null : fromAddress.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.TO_USER
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.TO_USER
     *
     * @mbg.generated
     */
    public String getToUser() {
        return toUser;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.TO_USER
     *
     * @param toUser the value for TBL_WALLET_BS_TX_RECORD.TO_USER
     *
     * @mbg.generated
     */
    public void setToUser(String toUser) {
        this.toUser = toUser == null ? null : toUser.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.TO_ADDRESS
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.TO_ADDRESS
     *
     * @mbg.generated
     */
    public String getToAddress() {
        return toAddress;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.TO_ADDRESS
     *
     * @param toAddress the value for TBL_WALLET_BS_TX_RECORD.TO_ADDRESS
     *
     * @mbg.generated
     */
    public void setToAddress(String toAddress) {
        this.toAddress = toAddress == null ? null : toAddress.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.AMOUNT
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.AMOUNT
     *
     * @param amount the value for TBL_WALLET_BS_TX_RECORD.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.STATUS
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.STATUS
     *
     * @param status the value for TBL_WALLET_BS_TX_RECORD.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_WALLET_BS_TX_RECORD.TRAN_TIME
     *
     * @return the value of TBL_WALLET_BS_TX_RECORD.TRAN_TIME
     *
     * @mbg.generated
     */
    public LocalDateTime getTranTime() {
        return tranTime;
    }

    /**
     *
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_WALLET_BS_TX_RECORD.TRAN_TIME
     *
     * @param tranTime the value for TBL_WALLET_BS_TX_RECORD.TRAN_TIME
     *
     * @mbg.generated
     */
    public void setTranTime(LocalDateTime tranTime) {
        this.tranTime = tranTime;
    }

	public String getHash() {
		return hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public String getCurrencyId() {
		return currencyId;
	}

	public void setCurrencyId(String currencyId) {
		this.currencyId = currencyId;
	}
	
	private WalletCurrency walletCurrency;

	public WalletCurrency getWalletCurrency() {
		return walletCurrency;
	}

	public void setWalletCurrency(WalletCurrency walletCurrency) {
		this.walletCurrency = walletCurrency;
	}
	
	
}