package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.Account;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface AccountDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT
     *
     * @mbg.generated
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT
     *
     * @mbg.generated
     */
    Account selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT
     *
     * @mbg.generated
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACCOUNT
     *
     * @mbg.generated
     */
    int updateById(Account record);
    
    Account findByUsername(String username);
    
    int updatePassword(Account account);
}