package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.EmailRecord;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface EmailRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMAIL_RECORD
     *
     * @mbg.generated
     */
    int insert(EmailRecord record);
    
    int updateById(EmailRecord record);
    
    EmailRecord selectById(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMAIL_RECORD
     *
     * @mbg.generated
     */
    List<EmailRecord> selectAll();
    
    List<EmailRecord> findByEntity(EmailRecord record);
}