package com.newtouch.blockchain.dao;


import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.newtouch.blockchain.entity.TxRecord;
import com.newtouch.blockchain.mybatis.MyBatisInterface;

@Repository
@MyBatisInterface
public interface TxRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    int insert(TxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    TxRecord selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    List<TxRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_TX_RECORD
     *
     * @mbg.generated
     */
    int updateById(TxRecord record);
    
    List<TxRecord> findByAddress(String address);
    
    Long findMaxBlockNumber();
    
    Long findMinBlockNumber();
    
    BigDecimal findSumTx();
    
    int findCount();
    
    List<TxRecord> findByPage(@Param("start") int start,@Param("size") int size);
    
    List<TxRecord> findByDate(@Param("startDate") String startDate,@Param("endDate") String endDate);
    
    TxRecord findByHash(String hash);
    
    List<TxRecord> findByAddressFrom(String address);
    
    List<TxRecord> findByAddressTo(String address);
    
    List<TxRecord> findByAddressFromAndDate(@Param("address") String address,@Param("startDate") String startDate,@Param("endDate") String endDate);
    
    List<TxRecord> findByAddressToAndDate(@Param("address") String address,@Param("startDate") String startDate,@Param("endDate") String endDate);

    BigDecimal findMountTxOut(@Param("address") String address);
    
    BigDecimal findMountTxIn(@Param("address") String address);
    
    BigDecimal findOutNumByAddress(@Param("address") String address);
    
    BigDecimal findInNumByAddress(@Param("address") String address);
    
}