package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletAccount;
import com.newtouch.blockchain.entity.WalletCurrency;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletCurrencyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    int insert(WalletCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    WalletCurrency selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    List<WalletCurrency> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_CURRENCY
     *
     * @mbg.generated
     */
    int updateById(WalletCurrency record);
    
    List<WalletCurrency> findByStatus(String status);
    
    List<WalletCurrency> findByAccount(String accountId);
    
    List<WalletCurrency> findByEntity(WalletCurrency walletCurrency);
    List<WalletCurrency> findByAccountEntity(WalletAccount walletAccount);
}