package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletAccount;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletAccountDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    int insert(WalletAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    WalletAccount selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    List<WalletAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT
     *
     * @mbg.generated
     */
    int updateById(WalletAccount record);
    
    int updateStatus(WalletAccount record);
    
    WalletAccount findByUsername(String username);
    
    List<WalletAccount> findByEntity(WalletAccount walletAccount);
}