package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletNode;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletNodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_NODE
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_NODE
     *
     * @mbg.generated
     */
    int insert(WalletNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_NODE
     *
     * @mbg.generated
     */
    WalletNode selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_NODE
     *
     * @mbg.generated
     */
    List<WalletNode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_NODE
     *
     * @mbg.generated
     */
    int updateById(WalletNode record);
    
    WalletNode findByUrl(String url);
    
    List<WalletNode> findByEntity(WalletNode node);
}