package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletBcTxRecord;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletBcTxRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BC_TX_RECORD
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BC_TX_RECORD
     *
     * @mbg.generated
     */
    int insert(WalletBcTxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BC_TX_RECORD
     *
     * @mbg.generated
     */
    WalletBcTxRecord selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BC_TX_RECORD
     *
     * @mbg.generated
     */
    List<WalletBcTxRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BC_TX_RECORD
     *
     * @mbg.generated
     */
    int updateById(WalletBcTxRecord record);
    
    public Long findMaxBlockNumber();
    
    public Long findMinBlockNumber();
    
    public Long findCount();
}