package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletBsTxRecord;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import com.newtouch.blockchain.vo.WalletBsTxRecordVO;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletBsTxRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    int insert(WalletBsTxRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    WalletBsTxRecord selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    List<WalletBsTxRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_BS_TX_RECORD
     *
     * @mbg.generated
     */
    int updateById(WalletBsTxRecord record);
    
    List<WalletBsTxRecord> findByBsTxVO(WalletBsTxRecordVO walletBsTxRecordVO);
    
    List<WalletBsTxRecord> findByBsTx(WalletBsTxRecord record);
    
    List<WalletBsTxRecord> findByUsername(String username);
    
    List<WalletBsTxRecord> findByDate(@Param(value = "startDate") String startDate,@Param("endDate") String endDate);
}