package com.newtouch.blockchain.dao;

import com.newtouch.blockchain.entity.WalletAccountCurrency;
import com.newtouch.blockchain.mybatis.MyBatisInterface;
import java.util.List;
import org.springframework.stereotype.Repository;

@Repository
@MyBatisInterface
public interface WalletAccountCurrencyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT_CURRENCY
     *
     * @mbg.generated
     */
    int deleteById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT_CURRENCY
     *
     * @mbg.generated
     */
    int insert(WalletAccountCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT_CURRENCY
     *
     * @mbg.generated
     */
    WalletAccountCurrency selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT_CURRENCY
     *
     * @mbg.generated
     */
    List<WalletAccountCurrency> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_WALLET_ACCOUNT_CURRENCY
     *
     * @mbg.generated
     */
    int updateById(WalletAccountCurrency record);
    
    List<WalletAccountCurrency> findByAccountCurrency(WalletAccountCurrency walletAccountCurrency);
}